<?php $this->headTitle('恋愛診断テスト管理画面') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php include(dirname(__FILE__).'/../common/header.phtml');?>
<div class="title">
	<h2>恋愛診断テスト<br>樹形図グラフ</h2>
</div>
<div>
	<table class="table table-bordered">
		<tbody>
			<tr class="active">
				<th>問題1</th>
				<th>問題2</th>
				<th>結果</th>
			</tr>
			<tr>
				<td><a href="#">1-1</a></td>
				<td><a href="#">2-1</a></td>
				<td><a href="#">キモオタタイプ</a></td>
			</tr>
			<tr>
				<td></td>
				<td><a href="#">2-2</a></td>
				<td><a href="#">モテ男子</a></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td><a href="#">矢さお</a></td>
			</tr>
		</tbody>
	</table>
</div>

