<?php $testTitle = $this->title?>
<?php $this->headTitle($testTitle.'テスト管理画面') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php include(dirname(__FILE__).'/../common/header.phtml');?>
<div class="title">
	<h2><?php echo $testTitle ?>テスト<br>樹形図グラフ</h2>
</div>
<div>
	<table class="table table-bordered">
		<tbody>
			<?php $i = 1; ?>
			<?php foreach ($this->array as $values) : ?>
				<tr class="active">
					<?php if($i === count($this->array)): ?>
						<th>結果</th>
					<?php else: ?>
						<th>問題<?php echo $i; ?></th>
					<?php endif; ?>
				<?php $j = 1; ?>
				<?php foreach ($values as $value) :?>
					<?php if($i === count($this->array)): ?>
						<?php if($value === "") :?>
							<td><a href="type/<?php echo $j ?>/">入力する</a></td>
						<?php else : ?>
							<td><a href="type/<?php echo $j ?>/"><?php echo $value; ?></a></td>
						<?php endif; ?>
					<?php else: ?>
						<td><a href="/admin/user/<?php echo $testTitle;?>/<?php echo $testId;?>/<?php echo $value; ?>/"><?php echo $value; ?></a></td>
					<?php endif; ?>
					<?php $j++; ?>
				<?php endforeach; ?><br>
				<?php $i++; ?>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

