<?php $this->headTitle('問題番号2-2入力') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<h2 style="text-align:center; margin:50px;">問題番号3-2</h2>
<div style="width:60%; margin:auto;">
<textarea class="form-control" rows="10"></textarea>
</div>
<div style="margin:auto; width:60%;margin-top:40px;">
	<div class="row">
		<div class="col-xs-2 col-xs-offset-4">
			<a href="#" class="btn btn-primary">戻る</a>
		</div>
		<div class="col-xs-2">
			<a href="#" class="btn btn-primary">登録</a>
		</div>
	</div>		
</div>
