<?php $this->headTitle('タイトル入力') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php include(dirname(__FILE__).'/../common/header.phtml');?>
<h2>タイトル作成・タイプ数選択画面</h2>
<form action="/admin/type/" method="post">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-2">
      <h2>タイトル</h2>
    </div>
    <div class="col-xs-3">
      <input type="text" class="form-control" name="title">
    </div>
    <div class="col-xs-4">
      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        説明
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 col-xs-offset-2">
      <h2>タイプ数</h2>
    </div>
    <div class="col-xs-1">
      <input type="text" class="form-control" name="type">
    </div>
    <div class="col-xs-4 col-xs-offset-2">
      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        説明
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 col-xs-offset-5">
      <input type="submit" class="btn btn-primary" value="戻る">
      <input type="submit" class="btn btn-primary" value="進む">
    </div>
  </div> 
</form>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

  