<?php $this->headTitle('恋愛診断テストトップ') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/test.css')?>
<div class="question">
    <a href="1-1/">
      <h2 style="font-family: 'Lobster', cursive; margin-left:10px;">
      	<?php echo $this->title; ?></h2>
    </a>
</div>

