<?php $this->headTitle('TestMaker') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<div class="top" style="background-image: url('/img/top2.jpg');background-position: center;height: 580px;margin-top:50px; background-repeat: no-repeat;">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-8">
      <a href="#" style="margin-top:140px;" class="btn btn-primary"><h2>テスト作成</h2></a>
    </div>
  </div>
</div>

