<?php $this->headTitle('管理画面トップ') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/question.css')?>
<div class="title">
    <h1>恋愛診断テスト</h1>
  </div>
  <div class="question">
    <h2 style="font-family: 'Lobster', cursive; margin-left:10px;">QUESTION2</h2>
    <span>あなたの好きなタイプはほげほげである。</span>
  </div>
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-3">
      <div class="yes">
        <a href="#">YES</a>
      </div>
    </div>
    <div class="col-xs-2">
    </div>
    <div class="col-xs-3">
      <div class="no">
        <a href="#">No</a>
      </div>
    </div>
    <div class="col-xs-2">  
</div>

