<?php $this->headTitle($this->title.'テスト質問') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/question.css')?>
<div class="title">
    <h1><?php echo $this->title; ?></h1>
  </div>
  <div class="question">
    <h2 style="font-family: 'Lobster', cursive; margin-left:10px;">QUESTION<?php echo $this->question[0]; ?></h2>
    <span><?php echo $this->result['CONTENTS']?></span>
  </div>
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-3">
      <div class="yes">
        <a href="../<?php echo $this->question[0]+1; ?>-<?php echo $this->question[1] ?>/">YES</a>
      </div>
    </div>
    <div class="col-xs-2">
    </div>
    <div class="col-xs-3">
      <div class="no">
        <a href="../<?php echo $this->question[0]+1; ?>-<?php echo $this->question[1]+1; ?>/">No</a>
      </div>
    </div>
    <div class="col-xs-2">  
</div>

