<?php $this->headTitle('管理画面タイプ入力') ?>
<?php $this->headMeta()->appendName('keywords', '') ?>
<?php $this->headMeta()->appendName('description', '') ?>
<?php $this->headMeta()->appendName('robots', 'noindex,nofollow') ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/type.css')?>
<?php include(dirname(__FILE__).'/../common/header.phtml');?>

<div class="title">
	<div class="row">
		<div class="col-xs-3">
			<h2>タイプ入力画面</h2>
		</div>
		<div class="col-xs-2 col-xs-offset-5">
			<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">説明</button>
		</div>
	</div>
</div>

<div class="contents">
	<div class="row">
	  <div class="col-xs-3">
	    <h2>タイプ1</h2>
	  </div>
	  <div class="col-xs-3">
	  	<span>タイトル名</span>
	    <input type="text" class="form-control">
	  </div>
	  <div class="col-xs-6">
	  	<span>タイトル名</span>
	  	<textarea class="form-control" rows="10"></textarea>
	  </div>
	</div>
</div>
<div class="contents">
	<div class="row">
	  <div class="col-xs-3">
	    <h2>タイプ2</h2>
	  </div>
	  <div class="col-xs-3">
	  	<span>タイトル名</span>
	    <input type="text" class="form-control">
	  </div>
	  <div class="col-xs-6">
	  	<span>説明</span>
	  	<textarea class="form-control" rows="10"></textarea>
	  </div>
	</div>
</div>


